const COORDINATES = {
  DEFAULT: {
    LATITUDE: -27.2092052,
    LONGITUDE: -49.6401091,
  },
} as const;

const MAX_DISTANCE_IN_KILOMETERS = 0.1;

export { COORDINATES, MAX_DISTANCE_IN_KILOMETERS };
